pipeline {
  agent {
      label 'java-docker-deploy-slave'
  }
  
  stages {
    stage('Cloning Git') {
      steps {
        git 'https://github.com/Joel-alt/simpleProject.git'
      }
    }
    stage('Install dependencies') {
      steps {
        script{
            try  {
                dir("client") {
                  sh 'npm install'
                }
                dir("server") {
                  sh 'npm install'
                }
            } catch (err) {
                discordSend description: 'The installation failed', webhookURL: 'https://discord.com/api/webhooks/1125680197648269312/GiYNn6Dft6Py7k2nydjpwKZPy4r2-TmpoBY6dgfIz5vl-_AAn4Z8TKsOFz0bNduMM99J'
            }
        }
      }
    }
    stage('Run project') {
      steps{
        script{
            try  {
                sh 'concurrently "cd server && node index.js" "cd client && npm start"'
            } catch (err) {
                discordSend description: 'Failed to run project', webhookURL: 'https://discord.com/api/webhooks/1125680197648269312/GiYNn6Dft6Py7k2nydjpwKZPy4r2-TmpoBY6dgfIz5vl-_AAn4Z8TKsOFz0bNduMM99J'
            }
        }
      }
    }
  }
}
